services:
  auth:
    env_file:
        - sources/auth/.env # Spécifie le fichier .env à utiliser
    build:
      context: ./sources/auth
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    volumes:
      - ./sources/auth:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongo:27017/app_db
    depends_on:
      - auth-mongo
    networks:
      - ticketing

  auth-mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ticketing


volumes:
  mongo_data:

networks:
  ticketing:
    external: true
